
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed2;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.NodeView mainTable;

	private global::Gtk.Button saveButton;

	private global::Gtk.Button addButton;

	private global::Gtk.Button removeButton;

	private global::Gtk.Button loadButton;

	private global::Gtk.Button htmlButton;

	private global::Gtk.Button browswerButton;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed2 = new global::Gtk.Fixed();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.mainTable = new global::Gtk.NodeView();
		this.mainTable.WidthRequest = 500;
		this.mainTable.HeightRequest = 300;
		this.mainTable.CanFocus = true;
		this.mainTable.Name = "mainTable";
		this.GtkScrolledWindow.Add(this.mainTable);
		this.fixed2.Add(this.GtkScrolledWindow);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.GtkScrolledWindow]));
		w2.X = 4;
		w2.Y = 7;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.saveButton = new global::Gtk.Button();
		this.saveButton.CanFocus = true;
		this.saveButton.Name = "saveButton";
		this.saveButton.UseUnderline = true;
		this.saveButton.Label = global::Mono.Unix.Catalog.GetString("Save");
		this.fixed2.Add(this.saveButton);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.saveButton]));
		w3.X = 78;
		w3.Y = 375;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.addButton = new global::Gtk.Button();
		this.addButton.CanFocus = true;
		this.addButton.Name = "addButton";
		this.addButton.UseUnderline = true;
		this.addButton.Label = global::Mono.Unix.Catalog.GetString("Add");
		this.fixed2.Add(this.addButton);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.addButton]));
		w4.X = 17;
		w4.Y = 331;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.removeButton = new global::Gtk.Button();
		this.removeButton.CanFocus = true;
		this.removeButton.Name = "removeButton";
		this.removeButton.UseUnderline = true;
		this.removeButton.Label = global::Mono.Unix.Catalog.GetString("Remove");
		this.fixed2.Add(this.removeButton);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.removeButton]));
		w5.X = 65;
		w5.Y = 331;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.loadButton = new global::Gtk.Button();
		this.loadButton.CanFocus = true;
		this.loadButton.Name = "loadButton";
		this.loadButton.UseUnderline = true;
		this.loadButton.Label = global::Mono.Unix.Catalog.GetString("Load");
		this.fixed2.Add(this.loadButton);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.loadButton]));
		w6.X = 16;
		w6.Y = 375;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.htmlButton = new global::Gtk.Button();
		this.htmlButton.CanFocus = true;
		this.htmlButton.Name = "htmlButton";
		this.htmlButton.UseUnderline = true;
		this.htmlButton.Label = global::Mono.Unix.Catalog.GetString("Save as html");
		this.fixed2.Add(this.htmlButton);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.htmlButton]));
		w7.X = 430;
		w7.Y = 330;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.browswerButton = new global::Gtk.Button();
		this.browswerButton.CanFocus = true;
		this.browswerButton.Name = "browswerButton";
		this.browswerButton.UseUnderline = true;
		this.browswerButton.Label = global::Mono.Unix.Catalog.GetString("Open in browswer");
		this.fixed2.Add(this.browswerButton);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.browswerButton]));
		w8.X = 270;
		w8.Y = 331;
		this.Add(this.fixed2);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 564;
		this.DefaultHeight = 435;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.saveButton.Clicked += new global::System.EventHandler(this.OnSaveButtonClicked);
		this.addButton.Clicked += new global::System.EventHandler(this.OnAddButtonClicked);
		this.removeButton.Clicked += new global::System.EventHandler(this.OnRemoveButtonClicked);
		this.loadButton.Clicked += new global::System.EventHandler(this.OnLoadButtonClicked);
		this.htmlButton.Clicked += new global::System.EventHandler(this.OnHtmlButtonClicked);
		this.browswerButton.Clicked += new global::System.EventHandler(this.OnBrowswerButtonClicked);
	}
}
